#!/usr/bin/env python3

from .RoutingProfile import RoutingProfile
from .RouteNetwork import RouteNetwork
from .POIDataset import POIDataset
from .Scenario import Scenario

from functools import partial
from pathlib import Path

class Environment():
    """
    Environment is a class to set default options for many of the tebetebe classes.
    Namely, this is used to specify the directory for temporary files generated by
    compilation.
    """
    def __init__(self, **kwargs):

        ## Set all env options to this class (set tmp_dir as a Path)
        for k_name, kwarg in kwargs.items():
            setattr(self, k_name, Path(kwarg) if k_name == "tmp_dir" else kwarg)

        self.RoutingProfile = partial(RoutingProfile, **kwargs)
        self.RouteNetwork = partial(RouteNetwork, **kwargs)
        self.POIDataset = partial(POIDataset, **kwargs)
        self.Scenario = partial(Scenario, **kwargs)

        self.RouteNetwork.from_overpass = partial(RouteNetwork.from_overpass, **kwargs)
        self.POIDataset.from_overpass = partial(POIDataset.from_overpass, **kwargs)
